name: "バグレポート - Bug report"
description: "このフィルタが引き起こしている問題をオーナーに報告します（「Get started」をクリックしてフォームを展開する👉） - Create a report to help us improve"
title: "なにかがおかしいよ（変更してお使い下さい）"
labels: ["bug"]
assignees:
  - STSynthe
body:
  - type: markdown
    attributes:
      value: "報告ありがとうございます。見出しの横に「*」の印がついたフォームは入力必須です。"
  - type: textarea
    id: url
    attributes:
      label: "URL"
      description: "問題を引き起こしてるウェブサイトURL"
      placeholder: "https://example.net/campaign/\r\nhttps://example.org/"
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: "Bad part"
      description: "表示の乱れや動作不良（logでも可）"
    validations:
      required: false
  - type: textarea
    id: original
    attributes:
      label: "Original"
      description: "本来の状態（提案可能な修正コードでも可）"
    validations:
      required: false
  - type: textarea
    id: oe
    attributes:
      label: "Operating environment"
      description: "環境（OS、ブラウザ、拡張機能、購読してるフィルタなどを分かる範囲で）"
      value: "- OS: Windows? macOS?\r\n- Browser: \r\n- Extension: Adblock Plus\r\n- Subscriptions: EasyList?, ABP Japanese filters(Edited by えむ/STSynthe)"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: "Agree"
      description: "このIssueをサブミットすることで、あなたは[`README.md`](https://stsynthe.github.io/abp-japanese-filters/)の内容を理解・同意したことになります。"
      options:
        - label: "**同意する - I agree**"
          required: true
